import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

import Header from '../components/common/header'

const questionFile = require('./questions.json')

export default function Home() {
  const [ currentQuestion, setCurrentQuestion ] = useState(questionFile.startQuestion)

  function setNewQuestion(ref){
    let nextQuestion = null
    
    if(ref.redirectToEnding != null){
      nextQuestion = questionFile.endings[ref.redirectToEnding]
    }
    else nextQuestion = ref

    console.log(nextQuestion)
    nextQuestion.lastQuestion = { ...currentQuestion }

    setCurrentQuestion(nextQuestion)
  }

  function lastQuestion(){
    setCurrentQuestion(currentQuestion.lastQuestion)
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>PHILCOIN Questionnaire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Fraud Avoidance
        </h1>
        <div className={styles.questions}>
          {currentQuestion.lastQuestion != null && <div onClick={() => lastQuestion()} style={{ style: 10 }} className={styles.questionBack}>undo</div>}
          <div className={styles.questionText}>
            <h2>{currentQuestion?.title}</h2>
            {currentQuestion?.desc && <p>{currentQuestion?.desc}</p>}
          </div>
          {(currentQuestion.option1Text || currentQuestion.option2Text) && <div className={styles.questionButtons}>
            <div onClick={() => setNewQuestion(currentQuestion.option1Followup)} className={styles.questionButton}>{currentQuestion.option1Text}</div>
            <div onClick={() => setNewQuestion(currentQuestion.option2Followup)} className={styles.questionButton}>{currentQuestion.option2Text}</div>
          </div>}
        </div>
      </main>
    </div>
  )
}